name: mobile_parking_app
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_stripe: ^10.1.1
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.4
  http: ^1.1.0
  intl: ^0.18.1
  # localization: ^2.1.0
  uuid: ^4.1.0
  equatable: ^2.0.5
  transparent_image_button: ^1.0.0
  image_picker: ^1.1.1
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
