name: 'Deploy Terraform to GCP'

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  prepare-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Zip Flask code
      run: zip -r backend_flask/flask_files.zip backend_flask/*
      working-directory: ${{ github.workspace }}
    
    - name: Zip Stripe code
      run: zip -r stripe_api/stripe_files.zip stripe_api/*
      working-directory: ${{ github.workspace }}

    - name: Upload Flask ZIP as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: flask-files
        path: ${{ github.workspace }}/backend_flask/flask_files.zip


  terraform:
    name: 'Terraform'
    needs: prepare-zip
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Download Flask ZIP
      uses: actions/download-artifact@v2
      with:
        name: flask-files
        path: backend_flask/

    
    - name: Add tf vars
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        echo "projectId = \"$PROJECT_ID\"" >  ${{ github.workspace }}/terraform_conf/values.tfvars

    - name: Create SA kay
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" > ${{ github.workspace }}/terraform_conf/key_app.json

    - name: Initialize Terraform
      run: terraform -chdir=${{ github.workspace }}/terraform_conf/ init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform_conf/key_app.json
        
    # - name: Import app engine application
    #   run: terraform -chdir=${{ github.workspace }}/terraform_conf/ import -var-file="${{ github.workspace }}/terraform_conf/values.tfvars" google_app_engine_application.app app 
    #   env:
    #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform_conf/key_app.json

    - name: Apply Terraform
      run: terraform -chdir=${{ github.workspace }}/terraform_conf/ apply -var-file="${{ github.workspace }}/terraform_conf/values.tfvars" -auto-approve 
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform_conf/key_app.json
